#!/bin/bash
# This script generates a project file for pylupdate4.

echo "SOURCES = \\" > maestro.pro

#grep -Rl --include=*.py 'translate(' ../maestro | sed 's/^/    /' | sed 's/$/ \\/' >> maestro.pro
find ../maestro -name *.py | grep -v translations.py | grep -v resources.py | sed 's/^/    /' | sed 's/$/ \\/' | sort >> maestro.pro


echo "" >> maestro.pro
echo "TRANSLATIONS = maestro.de.ts maestro.en.ts" >> maestro.pro
echo "CODECFORTR = UTF-8" >> maestro.pro
